### ISSUE TITLE
Component Tree feature

### ISSUE THREAD

**Issue by dungngminh** [dungngminh/app_creaty#30]
## Todo
- [x] Tree
- [x] Press to select widget
- [x] Show selected status when widget is selected
- [x] Right button to select option:
- [x] Wrap in function
- [x] Delele function
